"use client";

import { motion } from "framer-motion";
import { Delete, Fingerprint, LockKeyhole } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

export default function Unlock(){
  const router=useRouter(); const [pin,setPin]=useState(""); const [error,setError]=useState(false);
  const accessCode = "200410";
  useEffect(()=>{if(localStorage.getItem('arena-unlocked')==='true')router.replace('/dashboard')},[router]);
  const add=(n:string)=>{if(pin.length>=6)return;setError(false);const next=pin+n;setPin(next);if(next.length===6){setTimeout(()=>{if(next===accessCode){localStorage.setItem('arena-unlocked','true');router.push('/dashboard')}else{setError(true);setPin("")}},180)}};
  return <main className="unlock"><div className="ambient a"/><div className="ambient b"/><motion.section initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.55}} className="unlock-card"><div className="unlock-brand"><i>A</i><span>ARENA</span></div><div className="lock-icon"><LockKeyhole size={20}/></div><p className="unlock-label">ESPACE PERSONNEL SÉCURISÉ</p><h1>Bienvenue, Mourad.</h1><p className="unlock-copy">Entre ton code personnel pour accéder à ton arène.</p><div className={`pin-dots ${error?'error':''}`}>{Array.from({length:6},(_,i)=><i key={i} className={i<pin.length?'filled':''}/>)}</div><div className="keypad">{[1,2,3,4,5,6,7,8,9].map(n=><button aria-label={`Chiffre ${n}`} onClick={()=>add(String(n))} key={n}>{n}</button>)}<button className="bio" aria-label="Déverrouillage biométrique"><Fingerprint size={19}/></button><button aria-label="Chiffre 0" onClick={()=>add('0')}>0</button><button className="delete" aria-label="Supprimer" onClick={()=>setPin(p=>p.slice(0,-1))}><Delete size={18}/></button></div><p className="unlock-note">Code personnel requis pour déverrouiller ton espace.</p></motion.section><style jsx>{`
.unlock{min-height:100vh;display:grid;place-items:center;background:#0a0a0f;overflow:hidden;position:relative;padding:24px}.ambient{position:absolute;width:55vw;height:55vw;border-radius:50%;filter:blur(70px);opacity:.12}.ambient.a{background:#d4af37;top:-33vw;left:-12vw}.ambient.b{background:#22d3ee;bottom:-38vw;right:-15vw}.unlock-card{width:min(390px,100%);position:relative;text-align:center;padding:42px 34px 30px;background:linear-gradient(145deg,rgba(31,41,55,.74),rgba(17,24,39,.77));border:1px solid rgba(255,255,255,.09);border-radius:20px;box-shadow:0 24px 50px -25px #000;backdrop-filter:blur(20px) saturate(180%)}.unlock-brand{display:flex;align-items:center;justify-content:center;gap:9px;font:700 14px 'Plus Jakarta Sans';letter-spacing:.17em}.unlock-brand i{font:700 16px 'Space Grotesk';font-style:normal;color:#d4af37;border:1px solid rgba(212,175,55,.6);border-radius:7px;width:27px;height:27px;display:grid;place-items:center}.lock-icon{display:grid;place-items:center;width:48px;height:48px;border-radius:14px;margin:33px auto 14px;background:rgba(212,175,55,.1);color:#d4af37;border:1px solid rgba(212,175,55,.18);box-shadow:0 0 27px rgba(212,175,55,.09)}.unlock-label{font:10px 'JetBrains Mono';letter-spacing:.13em;color:#9ca3af}.unlock h1{font:700 26px 'Plus Jakarta Sans';letter-spacing:-.05em;margin:11px 0 8px}.unlock-copy{font-size:12px;line-height:1.65;color:#9ca3af;margin:0}.pin-dots{display:flex;justify-content:center;gap:12px;margin:29px 0 24px}.pin-dots i{width:10px;height:10px;border:1px solid #667080;border-radius:50%;transition:all .18s cubic-bezier(.16,1,.3,1)}.pin-dots i.filled{background:#d4af37;border-color:#d4af37;box-shadow:0 0 12px rgba(212,175,55,.5);transform:scale(1.14)}.pin-dots.error i{background:#c53030}.keypad{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.keypad button{height:45px;border:1px solid transparent;border-radius:9px;color:#ecedf0;background:rgba(255,255,255,.035);font:500 16px 'Space Grotesk';transition:all .18s cubic-bezier(.16,1,.3,1)}.keypad button:hover,.keypad button:active{border-color:rgba(212,175,55,.25);background:rgba(212,175,55,.09);color:#f5dc80;transform:scale(.97)}.keypad button.bio,.keypad button.delete{color:#9ca3af;display:grid;place-items:center}.unlock-note{font:9px 'JetBrains Mono';color:#687080;line-height:1.55;margin:21px 0 0}@media(max-width:420px){.unlock-card{padding:35px 25px 25px}}
`}</style></main>
}
